### ISSUE TITLE
Update cargo features syntax?

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/parquet-wasm#115]
https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features

**Comment by kylebarron** [comment]
For one you can make the optional dependencies for compression easier. Instead of having `parquet/brotli` and `parquet2/brotli`, you can just have a `brotli` feature with 

```toml
[features]
serde = ["parquet?/brotli", "parquet2?/brotli"]
```

And similarly have `all_supported_compressions` instead of `parquet_supported_compressions` and `parquet2_supported_compressions`

Just need to document that cargo 1.60.0 is required.
